<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Asset Report</title>
    <style>
        body {
            font-family: sans-serif;
            padding: 20px;
            /* Your original border style */
            border: 4px double #333; 
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #ddd;
            padding-bottom: 20px;
            margin-bottom: 20px;
        }
        .meta-info {
            width: 100%;
            margin-bottom: 20px;
            font-size: 12px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-transform: uppercase;
        }
        /* Zebra Striping */
        .table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        /* Status Colors */
        .status-good { color: green; font-weight: bold; }
        .status-damaged { color: red; font-weight: bold; }
        .status-maintenance { color: orange; font-weight: bold; }
        
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #777;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
        /* Prevent table rows from splitting across pages */
        tr { page-break-inside: avoid; }
    </style>
</head>
<body>

    <!-- HEADER -->
    <div class="header">
        <!-- Logo -->
        <img src="{{ public_path('storage/icon/tarumt.png') }}" style="width: 100px; height: auto; margin-bottom: 10px;" alt="Logo">
        
        <h1 style="margin: 0; text-transform: uppercase; font-size: 20px;">Asset Inventory Report</h1>
        <p style="margin: 5px 0 0; color: #555; font-size: 12px;">TAR UMT Facility Management System</p>
    </div>

    <!-- META INFO (Date & Summary) -->
    <table class="meta-info">
        <tr>
            <td style="text-align: left;">
                <strong>Generated By:</strong> {{ Auth::user()->name ?? 'System Admin' }}<br>
                <strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}
            </td>
            <td style="text-align: right;">
                <strong>Total Assets:</strong> {{ count($assets) }}<br>
                <strong>Filter:</strong> {{ $filter ?? 'All Assets' }}
            </td>
        </tr>
    </table>

    <!-- ASSET TABLE -->
    <table class="table">
        <thead>
            <tr>
                <th style="width: 40px;">ID</th>
                <th>Asset Name</th>
                <th>Serial No.</th>
                <th>Facility / Location</th>
                <th style="width: 80px;">Status</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @foreach($assets as $asset)
            <tr>
                <td>#{{ $asset->id }}</td>
                <td>
                    {{ $asset->name }} <br>
                    <span style="color: #888; font-size: 10px;">{{ $asset->type }}</span>
                </td>
                <td>{{ $asset->serial_number }}</td>
                <td>
                    {{ $asset->facility->name ?? 'Unassigned' }}
                </td>
                <td>
                    @php
                        $statusClass = match($asset->condition) {
                            'Good' => 'status-good',
                            'Damaged', 'Retired' => 'status-damaged',
                            'Maintenance' => 'status-maintenance',
                            default => ''
                        };
                    @endphp
                    <span class="{{ $statusClass }}">
                        {{ $asset->condition }}
                    </span>
                </td>
                <td>
                    {{ $asset->maintenance_note }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- FOOTER -->
    <div class="footer">
        <em>This is a computer-generated document. No signature is required.</em>
    </div>

</body>
</html>