<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Audit Log Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #2563eb;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            color: #666;
            margin: 5px 0 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #e2e8f0;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8fafc;
            color: #1e293b;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .badge {
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-created { background-color: #d1fae5; color: #065f46; }
        .badge-updated { background-color: #fed7aa; color: #92400e; }
        .badge-deleted { background-color: #fecaca; color: #991b1b; }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>TARUMT Facility Booking System</h1>
        <p>Security Audit Log Report</p>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%">ID</th>
                <th style="width: 15%">User</th>
                <th style="width: 10%">Action</th>
                <th style="width: 15%">Model</th>
                <th style="width: 15%">IP Address</th>
                <th style="width: 20%">Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
            <tr>
                <td>{{ $log->id }}</td>
                <td>
                    {{ $log->user->name ?? 'System' }}<br>
                    <small style="color: #666;">{{ $log->user->role ?? 'system' }}</small>
                </td>
                <td>
                    <span class="badge badge-{{ $log->action }}">
                        {{ $log->action }}
                    </span>
                </td>
                <td>
                    {{ class_basename($log->model_type) }} #{{ $log->model_id }}
                </td>
                <td>{{ $log->ip_address }}</td>
                <td>{{ $log->created_at->format('Y-m-d H:i:s') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Confidential Document • For Internal Use Only • Generated by System Admin
    </div>
</body>
</html>
